config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 

    root to: 'landing#index'
    resources :prendas
    resources :guardarropas do
      resources :atuendos
      get 'atuendo-aleatorio', to: 'atuendos#show_random'
    end

    get 'usuarios', to: 'usuarios#index'
    get '*path', to: 'errores#error_404', via: :all
    
  # post 'prendas', to: 'prendas#create'
  # get 'prendas/new', to: 'prendas#new'
  # get 'prendas', to: 'prendas#index'
  # get 'prendas/:id', to: 'prendas#show'
  # get 'prendas/:id/edit', to:'prendas#edit'
  # delete 'prendas/:id', to: 'prendas#destroy'
  # put 'prendas/:id', to: 'prendas#update'
  # patch 'prendas/:id', to: 'prendas#update'

end

app/models/guardarropa.rb
class Guardarropa < ApplicationRecord
    has_many :prendas
    has_many :atuendos
    belongs_to :usuario, required:true
end 

app/controllers/guardarropas_controller.rb
class GuardarropasController < ApplicationController

    before_action :set_guardarropa, only:[:show, :destroy, :update, :edit]

    def index
        @guardarropas = Guardarropa.where(usuario_id: current_usuario.id).paginate(page: params[:page], per_page: 4)
    end

    def new
        @guardarropa=Guardarropa.new
    end
    
    def create
        @guardarropa=Guardarropa.new(guardarropas_params)
        @guardarropa.usuario= current_usuario
        if @guardarropa.save
            redirect_to guardarropas_path,notice: t(:created)
        else
            redirect_to new_guardarropa_path
        end
    end

    def show

        if(validado?)
            @prendas=Prenda.where(guardarropa_id: @guardarropa.id).paginate(page: params[:page], per_page: 6)
        else
            redirect_to guardarropas_path, notice: t(:error)
        end
    end
    
    def edit
    end

    def destroy
        @prendas=Prenda.where(guardarropa_id: @guardarropa.id)
        @atuendos=@guardarropa.atuendos

        @prendas.each do |p|
            p.guardarropa_id= nil; 
            p.save!
        end 

        @atuendos.each do |a|
            a.destroy!
        end
        
        if @guardarropa.destroy
            redirect_to guardarropas_path, notice: t(:deleted)
        end
    end 

    def update
        if @guardarropa.update_attributes(guardarropas_params)
            redirect_to guardarropas_path, notice: t(:updated)
        else
            redirect_to edit_guardarropa_path
        end
    end


    private
    def guardarropas_params
       params.require(:guardarropa).permit(:nombre)     
    end

    def set_guardarropa
        @guardarropa= Guardarropa.find(params[:id])
    end

    def validado?
        set_guardarropa.usuario==current_usuario
    end
end

app/views/guardarropas/_atributos_prenda.html.erb
<% if(show) %>
<div>
      <tr>
        <th> <strong>Nombre</strong> </th>
        <th> <strong>Textura</strong> </th>
        <th> <strong>Color</strong> </th>
        <th> <strong>Color <br/>Secundario</strong> </th>
        <th> <strong>Tipo de Prenda</strong> </th>
        <th> </th>
      </tr>
</div>
<% end %>

app/views/guardarropas/_form.html.erb
<div>
<div class="new-edit-form">
<h1> <%= text %></h1>
<%= form_for guardarropa do |f|%>
    <p>
        <%= f.label :nombre%><br />
        <%= f.text_field :nombre %>
    </p>
    <div class="interact-btn">
        <%= button_tag :class => "interact-btn green" do %>
             <i class="fas fa-check"></i>
        <% end %>
        <%= link_to :back, :class => "interact-btn red" do %>
            <i class="fas fa-times"></i>
        <% end %>
    </div>
<%end%>
</div>

</div>

app/views/guardarropas/_guardarropa.html.erb
<div class="card">
    <div class="guardarropa-nombre">
        <p><%= guardarropa.nombre %></p>
    </div>
    <div class="action-btn action-btn-guardarropas">
    <%= link_to edit_guardarropa_path(guardarropa) do %>
        <i class="far fa-edit fa-2x"></i> 
    <% end %>

    <%= link_to guardarropa do%>
        <i class="far fa-eye fa-2x"></i>
    <% end %>

    <%= link_to guardarropa, method: :delete, data: { confirm: 'Estas Seguro?' } do%>
        <i class="far fa-trash-alt fa-2x"></i>
    <% end %>
    </div>
</div>

app/views/guardarropas/edit.html.erb
<%= render 'form', guardarropa: @guardarropa, text:"Editar" %>

app/views/guardarropas/index.html.erb
<div class="container guardarropas-view">
  <% @guardarropas.each do |g| %>
    <%= render 'guardarropa', guardarropa: g %>
  <%end%>
  <div class="interact-btn">
    <%= link_to "Crear Guardarropa", new_guardarropa_path%>
    <% if @guardarropas.present?%>
    <%= link_to "Crear Prenda", new_prenda_path%> 
    <% end %>
    <% if (Prenda.where(usuario_id: current_usuario, guardarropa_id: nil).count != 0 )%>
    <%= link_to "Prendas sueltas", prendas_path%>
    <% end %>
  </div> 
      <div class="paginacion">
        <%= will_paginate @guardarropas, :container=> false, previous_label: "Anterior", next_label: "Siguiente", inner_window: 1, outer_window: 0 %>
    </div>
</div>

app/views/guardarropas/new.html.erb
<%= render 'form', guardarropa: @guardarropa, text:"Crear" %>

app/views/guardarropas/show.html.erb
<div>
  <% if !@prendas.present? %>
    <h2 style = "font-family: 'Open Sans""> ¡Agrega tu primera prenda!</h2>
  <% end %>
  <div class="prendas-view">
    <table class="tabla">
        <tr>  <%= render 'atributos_prenda', show: @prendas.present? %> </tr>
        <% @prendas.each do |p| %>
            <%= render 'prendas/prenda', prenda: p, show_show: true %>
        <%end%>
    </table>
  </div>
  <div class= "interact-btn">
      <%= link_to "Agregar Prenda", new_prenda_path(:guardarropa_id => @guardarropa.id)%>
      <% if @prendas.present? %>
        <%= link_to "Crear Atuendo",  new_guardarropa_atuendo_path(:guardarropa_id => @guardarropa.id), class: "interact-btn" %>
        <%= link_to "Crear Atuendo Aleatorio",  "/guardarropas/#{@guardarropa.id}/atuendo-aleatorio", class: "interact-btn" %>
      <% end %>
      <% if @guardarropa.atuendos.present? %>
       <%= link_to "Ver Atuendos", guardarropa_atuendos_path(:guardarropa_id => @guardarropa.id) %>
      <% end %>
      <%= link_to "Volver", guardarropas_path %>
  </div>
  <div class="paginacion">
    <%= will_paginate @prendas, :container=> false, previous_label: "Anterior", next_label: "Siguiente", inner_window: 1, outer_window: 0 %>
  </div>
</div> 