config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 

    root to: 'landing#index'
    resources :prendas
    resources :guardarropas do
      resources :atuendos
      get 'atuendo-aleatorio', to: 'atuendos#show_random'
    end

    get 'usuarios', to: 'usuarios#index'
    get '*path', to: 'errores#error_404', via: :all
    
  # post 'prendas', to: 'prendas#create'
  # get 'prendas/new', to: 'prendas#new'
  # get 'prendas', to: 'prendas#index'
  # get 'prendas/:id', to: 'prendas#show'
  # get 'prendas/:id/edit', to:'prendas#edit'
  # delete 'prendas/:id', to: 'prendas#destroy'
  # put 'prendas/:id', to: 'prendas#update'
  # patch 'prendas/:id', to: 'prendas#update'

end

app/models/atuendo.rb
class Atuendo < ApplicationRecord
    belongs_to :prenda_cabeza, class_name: "Prenda" , required:false
    belongs_to :prenda_torso, class_name: "Prenda" , required:false
    belongs_to :prenda_piernas, class_name: "Prenda" , required:false
    belongs_to :prenda_pies, class_name: "Prenda" , required:false
    belongs_to :usuario
    #has_many   :prendas
    belongs_to :guardarropa, required:true

    enum estilo: [:formal, :informal]
    enum estacion: [:verano, :primavera, :invierno, :otoño]
    enum puntaje: [:Nefasto, :Malo, :Normal, :"Muy Bueno", :Excelente]
    
end

app/controllers/atuendos_controller.rb
class AtuendosController < ApplicationController

    before_action :set_guardarropa
    helper_method :ordenar_columna,:ordenar_direccion
    before_action :set_atuendo, only: [:show, :edit, :update, :destroy]
    
    def index

        if(validado?)
            if(!@guardarropa.atuendos.present?)
                redirect_to guardarropa_path(@guardarropa)
            else
                @atuendos=Atuendo.where(guardarropa_id: @guardarropa.id).order(ordenar_columna + " " + ordenar_direccion).paginate(page: params[:page], per_page: 6)
                
                if(params[:estilo] || params[:estacion])
                    @atuendos=@atuendos.where(estilo: params[:estilo]) if(params[:estilo] != "")
                    @atuendos=@atuendos.where(estacion: params[:estacion]) if(params[:estacion] != "")
                end
            end
        else
            redirect_to guardarropas_path, notice: t(:error)
        end
    end

    def show
    end    
    
    def destroy
        aId=set_atuendo.id
        if @atuendo.destroy
            redirect_to guardarropa_atuendos_path(:guardarropa_id => @guardarropa.id), notice: t(:deleted)
        end
    end 

    def show_random

        @atuendo=Atuendo.new
        @prenda_cabeza=  Guardarropa.find(params[:guardarropa_id]).prendas.joins(:prenda_tipo).where(prenda_tipos: {categoria: :cabeza}).order('RANDOM()').first
        @prenda_torso=   Guardarropa.find(params[:guardarropa_id]).prendas.joins(:prenda_tipo).where(prenda_tipos: {categoria: :torso}).order('RANDOM()').first
        @prenda_piernas= Guardarropa.find(params[:guardarropa_id]).prendas.joins(:prenda_tipo).where(prenda_tipos: {categoria: :piernas}).order('RANDOM()').first
        @prenda_pies=    Guardarropa.find(params[:guardarropa_id]).prendas.joins(:prenda_tipo).where(prenda_tipos: {categoria: :pies}).order('RANDOM()').first

        if(!@prenda_cabeza || !@prenda_torso || !@prenda_piernas || !@prenda_pies)
            redirect_to guardarropa_path(@guardarropa), notice: "¡Cuidado! Para crear un atuendo aleatorio necesitas al menos una prenda de cada tipo"
        end
        
    end

    def new
        @atuendo=Atuendo.new
    end

    def create
        @atuendo=Atuendo.new(atuendo_params)
        @atuendo.usuario=current_usuario

        if (@guardarropa.atuendos << @atuendo)
        redirect_to guardarropa_atuendos_path,notice: t(:created)  
        end
    end

    def edit
    end

    def update
        if @atuendo.update_attributes(atuendo_params)
            redirect_to guardarropa_atuendos_path, notice: t(:updated)
        else
            render edit_atuendo_path
        end
    end

    private
    def atuendo_params
       params.require(:atuendo).permit(:prenda_cabeza_id, :prenda_torso_id, :prenda_piernas_id, :prenda_pies_id, :puntaje, :estilo, :estacion)     
    end

    def set_atuendo
        @atuendo= Atuendo.find(params[:id].to_i)
    end

    def set_guardarropa
        @guardarropa= Guardarropa.find(params[:guardarropa_id].to_i)
    end

    def ordenar_columna
        Atuendo.column_names.include?(params[:columna]) ? params[:columna] : "puntaje"
    end

    def ordenar_direccion
        %w[asc desc].include?(params[:direccion]) ? params[:direccion] : "desc"
    end

    def validado?
        set_guardarropa.usuario=current_usuario;
    end
end

app/views/atuendos/_atributos_atuendo.html.erb
<% if(show) %>
<div>
        <th> <strong>Cabeza</strong> </th>
        <th> <strong>Torso</strong> </th>
        <th> <strong>Piernas</strong> </th>
        <th> <strong>Pies</strong> </th>
        <th> <strong>Estacion</strong> </th>
        <th> <strong>Estilo</strong> </th>
        <th> <strong><%= ordenable "puntaje", "Puntaje"%> </strong> </th>
</div>
<%else%>
<h1></h1>
<% end %>

app/views/atuendos/_atuendo.html.erb
<div>
<tr>
    <td>
            <%if(atuendo.prenda_cabeza.present?)%>
             <%= atuendo.prenda_cabeza.nombre %>
            <%else%>
                <%= link_to  "Seleccionar", edit_guardarropa_atuendo_path(:guardarropa_id => params[:guardarropa_id],:id => atuendo.id), class: "shared-links"  %>
            <%end%>
    </td>

    <td>
            <%if(atuendo.prenda_torso.present?)%>
             <%= atuendo.prenda_torso.nombre %>
            <%else%>
                <%= link_to  "Seleccionar", edit_guardarropa_atuendo_path(:guardarropa_id => params[:guardarropa_id],:id => atuendo.id), class: "shared-links" %>
            <%end%>
    </td>
    <td>
            <%if(atuendo.prenda_piernas.present?)%>
             <%= atuendo.prenda_piernas.nombre %>
            <%else%>
                <%= link_to  "Seleccionar", edit_guardarropa_atuendo_path(:guardarropa_id => params[:guardarropa_id],:id => atuendo.id), class: "shared-links"  %>
            <%end%>
    </td>
    <td>
            <%if(atuendo.prenda_pies.present?)%>
             <%= atuendo.prenda_pies.nombre %>
            <%else%>
                <%= link_to  "Seleccionar", edit_guardarropa_atuendo_path(:guardarropa_id => params[:guardarropa_id],:id => atuendo.id), class: "shared-links"  %>
            <%end%>
    </td>
    <td>
            <%if(atuendo.estacion)%>
             <%= atuendo.estacion %>
            <%else%>
                <%= link_to  "Seleccionar estacion", edit_guardarropa_atuendo_path(:guardarropa_id => params[:guardarropa_id],:id => atuendo.id), class: "shared-links"  %>               
            <%end%>
    </td>
    <td>
            <%if(atuendo.estilo)%>
             <%= atuendo.estilo %>
            <%else%>
                <%= link_to  "Seleccionar estilo", edit_guardarropa_atuendo_path(:guardarropa_id => params[:guardarropa_id],:id => atuendo.id), class: "shared-links"  %>               
            <%end%>
    </td>
    <td>
            <% if(atuendo.puntaje)%>
                <%= atuendo.read_attribute_before_type_cast(:puntaje)+1 %>
                (<%= atuendo.puntaje %>)
            <% else %>
                <%= link_to  "Seleccionar puntaje", edit_guardarropa_atuendo_path(:guardarropa_id => params[:guardarropa_id],:id => atuendo.id), class: "shared-links"  %>
            <% end %>
    </td>
    <td colspan="3">
    <div class="action-btn">
    <%= link_to edit_guardarropa_atuendo_path(:guardarropa_id => params[:guardarropa_id],:id => atuendo.id) do %>
        <i class="far fa-edit fa-2x"></i> 
    <% end %>

    <% if (show_show) %>
    <%= link_to guardarropa_atuendo_path(:guardarropa_id => params[:guardarropa_id],:id => atuendo.id)do%>
        <i class="far fa-eye fa-2x"></i>
    <% end %>
    <% end %>

   <%= link_to guardarropa_atuendo_path(:guardarropa_id => params[:guardarropa_id],:id => atuendo.id), method: :delete, data: { confirm: '¿Estas Seguro?' } do%>
        <i class="far fa-trash-alt fa-2x"></i>
    <% end %> 
    </td> 
    </div>
</tr>
</div>

app/views/atuendos/_form.html.erb
<div>
<div class="new-edit-form">

<h1> <%= text %></h1>
    <%= form_for [guardarropa, atuendo] do |f|%>
    <% PrendaTipo.categoria.keys.each do |categoria| %>
        <p>
            <%= f.label categoria%><br />
            <%= f.collection_select("prenda_#{categoria}_id", Prenda.joins(:prenda_tipo).where(prenda_tipos: {categoria: categoria}, guardarropa: guardarropa,usuario_id: current_usuario), :id, :nombre, selected: atuendo.send("prenda_#{categoria}_id"), :include_blank => true)%>
        </p>
    <% end %>

    <p>Estilo</p>
    <div class="radio">
    <% Atuendo.estilos.keys.each do |e| %>
        <%= f.radio_button :estilo, e %>
        <%= f.label :estilo, e%>
    <% end %>
    </div>

    
    <p>Estacion</p>
    <div class="radio">
    <% Atuendo.estacions.keys.each do |e| %>
        <%= f.radio_button :estacion, e%>
        <%= f.label :estacion, e%>
    <% end %>
    </div>

    <p>Calificacion</p>
    <div class="radio">
    <% Atuendo.puntajes.keys.each do |e| %>
        <%= f.radio_button :puntaje, e%>
        <%= f.label :puntaje, e%>
    <% end %>
    </div>

    <div class="interact-btn">
        <%= button_tag :class => "interact-btn green" do %>
             <i class="fas fa-check"></i>
        <% end %>
        <%= link_to :back, :class => "interact-btn red" do %>
            <i class="fas fa-times"></i>
        <% end %>
    </div>
<%end%>
</div>
</div>

app/views/atuendos/edit.html.erb
<%= render 'form',guardarropa: @guardarropa, atuendo: @atuendo, text:"Editar" %>

app/views/atuendos/index.html.erb
<div>
<div class="search-form">
<h1>Filtrar</h1>
<%= form_tag guardarropa_atuendos_path, method: :get do%>
 <div class="search-select">
 <%= select_tag :estilo, options_for_select(Atuendo.estilos.keys.to_a,selected: params[:estilo]),  :include_blank => true %> <!--selected-->
 <%= select_tag :estacion, options_for_select(Atuendo.estacions.keys.to_a, selected: params[:estacion]), :include_blank => true %>
 
<p class="interact-btn", style="margin-top: -1px;">
  <%= submit_tag "Buscar"%>
</p>

 </div>
<% end %>
</div>
  <div class="prendas-view">
    <table class="tabla">
      <tr>  <%= render 'atributos_atuendo', show: @atuendos.present? %> 
        <% @atuendos.each do |a| %>
            <%= render 'atuendo', atuendo: a, show_show: true %>
        <%end%>
       </tr>
    </table>
  </div>
    <div class="interact-btn">
        <%= link_to "Crear Atuendo", new_guardarropa_atuendo_path(params[:guardarropa_id])%>
        <%= link_to  "Volver", guardarropa_path(params[:guardarropa_id]) %>
    </div>
    
  <div class="paginacion">
    <%= will_paginate @prendas, :container=> false, previous_label: "Anterior", next_label: "Siguiente", inner_window: 1, outer_window: 0 %>
  </div>
  </div>
</div>

app/views/atuendos/new.html.erb
<%= render 'form',guardarropa: @guardarropa, atuendo: @atuendo, text:"Crear" %>

app/views/atuendos/show.html.erb
<div>
    <div class="prendas-view">
      <table class="tabla">

        <tr>  <%= render 'atributos_atuendo', show: true%> </tr>
        <tr>
            <%= render 'atuendo', atuendo: @atuendo, show_show: false %>
        </tr>
      </table>
    </div>
    <div class="interact-btn">
        <%= link_to  "Volver", guardarropa_atuendos_path(@atuendo.guardarropa) %>
    </div>
</div>

app/views/atuendos/show_random.html.erb
<div class="new-edit-form">
<h1> Atuendo Aleatorio </h1>
<%= form_for [@guardarropa, @atuendo] do |f|%>
    <p>
        <%= f.label "Prenda Cabeza"%><br />
        <%= f.text_field ("prenda_cabeza_id"),value: @prenda_cabeza.nombre, :readonly => true %>
        <%= f.hidden_field ("prenda_cabeza_id"), value: @prenda_cabeza.id %>
    </p>

    <p>
        <%= f.label "Prenda Torso"%><br />
        <%= f.text_field ("prenda_torso_id"),value: @prenda_torso.nombre, :readonly => true %>
        <%= f.hidden_field ("prenda_torso_id"), value: @prenda_torso.id %>
    </p>

    <p>
        <%= f.label "Prenda Piernas"%><br />
        <%= f.text_field ("prenda_piernas_id"),value: @prenda_piernas.nombre, :readonly => true %>
        <%= f.hidden_field ("prenda_piernas_id"), value: @prenda_piernas.id %>
    </p>

    <p>
        <%= f.label "Prenda Pies"%><br />
        <%= f.text_field ("prenda_pies_id"),value: @prenda_pies.nombre, :readonly => true %>
        <%= f.hidden_field ("prenda_pies_id"), value: @prenda_pies.id %>
    </p>

    <p>Estilo</p>
    <div class="radio">
    <% Atuendo.estilos.keys.each do |e| %>
        <%= f.radio_button :estilo, e %>
        <%= f.label :estilo, e%>
    <% end %>
    </div>

    
    <p>Estacion</p>
    <div class="radio">
    <% Atuendo.estacions.keys.each do |e| %>
        <%= f.radio_button :estacion, e%>
        <%= f.label :estacion, e%>
    <% end %>
    </div>

    <p>Calificacion</p>
    <div class="radio">
    <% Atuendo.puntajes.keys.each do |e| %>
        <%= f.radio_button :puntaje, e%>
        <%= f.label :puntaje, e%>
    <% end %>
    </div>

        <div class="interact-btn">
        <%= button_tag :class => "interact-btn green" do %>
             <i class="fas fa-check"></i>
        <% end %>
        <%= link_to guardarropa_path(@guardarropa.id), :class => "interact-btn red" do %>
            <i class="fas fa-times"></i>
        <% end %>
        <%= link_to "/guardarropas/#{@guardarropa.id}/atuendo-aleatorio", :class => "interact-btn blue" do %>
            <i class="fas fa-redo-alt"></i>
        <% end %>
    </div>

<% end %>
</div>