config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 

    root to: 'landing#index'
    resources :prendas
    resources :guardarropas do
      resources :atuendos
      get 'atuendo-aleatorio', to: 'atuendos#show_random'
    end

    get 'usuarios', to: 'usuarios#index'
    get '*path', to: 'errores#error_404', via: :all
    
  # post 'prendas', to: 'prendas#create'
  # get 'prendas/new', to: 'prendas#new'
  # get 'prendas', to: 'prendas#index'
  # get 'prendas/:id', to: 'prendas#show'
  # get 'prendas/:id/edit', to:'prendas#edit'
  # delete 'prendas/:id', to: 'prendas#destroy'
  # put 'prendas/:id', to: 'prendas#update'
  # patch 'prendas/:id', to: 'prendas#update'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Que me pongo | Vestite con nosotros!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>    	
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="public\fontawesome-free-5.13.0-web\fontawesome-free-5.13.0-web\css\all.css" />
     <%= csrf_meta_tags %>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ujs/1.2.2/rails.min.js" integrity="sha256-BbyWhCn0G+F6xbWJ2pcI5LnnpsnpSzyjJNVtl7ABp+M=" crossorigin="anonymous"></script>
  </head>
  <body>
  <div class="alerta">
    <div class="container" id="alert">
    <% flash.each do |type, msg| %>
          <p id="alert-text"><%= msg %><p>
      <% end %>
      <i class="far fa-times-circle" style="cursor: pointer;" id="close-alert"></i>
    </div>
  </div>
    <header>
    <div class="container nav-container">
      <h1><%= link_to "Que me pongo", '/' %></h1>
      <div class="nav-icon">
          <i class="fas fa-bars fa-3x"></i>
      </div>
      <nav class="navigation">
        <ul>
          <li><a href="https://www.facebook.com/queme.pongo.56884" target="_blank">Contacto</a></li>
          <li><p><%= link_to "Guardarropas", guardarropas_path%></p></li>
        <% if signed_in? %>
          <% if (Usuario.find(current_usuario.id).rol.nombre == "administrador") %>
            <li><%= link_to  "Usuarios", usuarios_path %></li>
          <% end %>
          <li><%= link_to "Salir", destroy_usuario_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Registrarse", new_usuario_registration_path %></li>
          <li><%= link_to "Ingresar", new_usuario_session_path %></li>
        <% end %>
        </ul>
      </nav>
    </div>
    </header>
    <main>
    <%= yield %> 
    </main>
    <%= yield :servicios%>
    <%= yield :contacto%>
    <footer>
      <div class="container">
        <p>Copyright © Que me pongo 2020</p>
        <div class="socialMedia">
          <i class="fab fa-facebook-square fa-3x"></i>
          <i class="fab fa-twitter-square fa-3x"></i>
          <a href="https://github.com/AgusBroz/TP_Programacion-lll"><i class="fab fa-github-square fa-3x"></i></a>
        </div>
        <div class="footer-text">
        <a href="#">Política de Privacidad</a>
        <a href="#">Términos y Condiciones</a>
        </div>
      </div>
    </footer>
    <script>
      //Alertas
      var alerta=document.getElementById("alert");
      var cerrar=document.getElementById("close-alert");
      cerrar.addEventListener("click", cerrarAlerta);

      function cerrarAlerta() {
        alerta.style.display='none'
      }
      if(document.getElementById("alert-text")){
        alerta.style.display='flex';
      }
    </script>
  </body>
</html>